package:
  name: apko
  version: 0.13.1
  epoch: 0
  description: Build OCI images using APK directly without Dockerfile
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/apko
      tag: v${{package.version}}
      expected-commit: 9ad04bd281c41bcd7db551a4337fe3274a7e8b8f

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0
      go-version: "1.21"

  - runs: |
      make apko
      install -m755 -D ./apko "${{targets.destdir}}"/usr/bin/apko

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/apko
    strip-prefix: v
    use-tag: true
