package:
  name: aws-ebs-csi-driver
  version: 1.26.0
  epoch: 0
  description: CSI driver for Amazon EBS.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - blkid
      - blockdev
      - e2fsprogs
      - e2fsprogs-extra
      - lsblk
      - mount
      - xfsprogs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
      tag: v${{package.version}}
      expected-commit: 09f742f7a545ea4d1d5fef333715e25cd2064c0d

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS

      make ARCH=$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      cp bin/aws-ebs-csi-driver ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - helm-chart-aws-ebs-csi-driver-
  github:
    identifier: kubernetes-sigs/aws-ebs-csi-driver
    strip-prefix: v
    tag-filter: v
