package:
  name: boring-registry
  version: 0.12.0
  epoch: 0
  description: Terraform Provider and Module Registry
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/TierMobility/boring-registry
      expected-commit: 1a8837b460476434c84b3b0cfcb1a44897c8ebbb
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: boring-registry
      ldflags: |
        -s -w
        -X github.com/TierMobility/boring-registry/version.Version="${{package.version}}"
        -X github.com/TierMobility/boring-registry/version.Commit="$(git rev-parse --verify HEAD --short)"
        -X github.com/TierMobility/boring-registry/version.Date="$(date -u +'%FT%T%z')"

  - uses: strip

update:
  enabled: true
  github:
    identifier: TierMobility/boring-registry
    strip-prefix: v
