package:
  name: cmake
  version: 3.27.0
  epoch: 0
  description: "cross-platform asynchronous I/O library"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - curl-dev
      - expat-dev
      - libarchive-dev
      - libuv-dev
      - ncurses-dev
      - rhash-dev
      - samurai
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.cmake.org/files/v3.27/cmake-${{package.version}}.tar.gz
      expected-sha256: aaeddb6b28b993d0a6e32c88123d728a17561336ab90e0bf45032383564d3cb8

  # Depending on system cppdap and jsoncpp would create a circular
  # dependency; thus, we use bundled ones.
  - runs: |
      ./bootstrap \
        --prefix=/usr \
        --mandir=/share/man \
        --datadir=/share/cmake \
        --docdir=/share/doc/cmake \
        --system-libs \
        --no-system-cppdap \
        --no-system-jsoncpp \
        --generator=Ninja \
        --parallel=$(nproc)

  - runs: |
      ninja

  - runs: |
      DESTDIR="${{targets.destdir}}" ninja install

  - uses: strip

update:
  enabled: true
  manual: true # be careful upgrading cmake as it is a core package
  release-monitor:
    identifier: 306
