package:
  name: deno
  version: 1.39.1
  epoch: 0
  description: "A modern runtime for JavaScript and TypeScript."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - glibc-dev
      - libLLVM-16
      - posix-libc-utils
      - protobuf-dev
      - protoc
      - python3
      - rust
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/denoland/deno/releases/download/v${{package.version}}/deno_src.tar.gz
      expected-sha256: fa747a8e26cd198f09d9d73ba6eaa111e843d28a896699489a665b5b39491437

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/deno ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: denoland/deno
    strip-prefix: v
