package:
  name: kine
  version: 0.11.2
  epoch: 0
  description: Run Kubernetes on MySQL, Postgres, sqlite, dqlite, not etcd.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k3s-io/kine
      tag: v${{package.version}}
      expected-commit: 5328e60ecffda5a758d77d85187ede696e3f7ca6
      destination: kine

  - runs: |
      cd kine
      ./scripts/build
      install -Dm755 ./bin/kine "${{targets.destdir}}/usr/bin/kine"

  - uses: strip

update:
  enabled: true
  github:
    identifier: k3s-io/kine
    strip-prefix: v
