package:
  name: lychee
  version: 0.13.0
  epoch: 0
  description: "Fast, async, stream-based link checker written in Rust"
  copyright:
    - license: Apache-2.0 AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lycheeverse/lychee
      tag: v${{package.version}}
      expected-commit: 75e80190fb39abd52ceabacce1073784c7bbaa5c

  - runs: |
      cargo build --release
      install -Dm755 target/release/lychee "${{targets.destdir}}"/usr/bin/lychee

  - uses: strip

update:
  enabled: true
  github:
    identifier: lycheeverse/lychee
    strip-prefix: v
