package:
  name: nuclei
  version: 3.1.3
  epoch: 0
  description: "yaml based vulnerability scanner"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - go
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/projectdiscovery/nuclei
      tag: v${{package.version}}
      expected-commit: c3b39be6050b0249a10613a214c905dc01872be9
      destination: nuclei

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin && cd nuclei
      go mod edit -replace=github.com/mholt/archiver@v3.1.1+incompatible=github.com/mholt/archiver/v3@v3.3.2 # CVE-2019-10743 Fixed
      go mod tidy
      go build cmd/nuclei/main.go
      cp main "${{targets.destdir}}"/usr/bin/nuclei

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: projectdiscovery/nuclei
