package:
  name: pulumi-language-yaml
  version: 1.4.5
  epoch: 1
  description: Pulumi Language SDK for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-yaml.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: 106f37cd0ab12839024b9b744cde4104d61e22b9

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/grpc@v1.57.1 github.com/go-git/go-git/v5@v5.11.0
      modroot: ${{package.name}}

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          set -x

          export CGO_ENABLED=0 GO111MODULE=on
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-yaml" \
            -ldflags="-s -w -X github.com/pulumi/pulumi-yaml/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-yaml/
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-yaml
    strip-prefix: v
