package:
  name: pulumi-language-yaml
  version: 1.4.4
  epoch: 0
  description: Pulumi Language SDK for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-yaml.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: f6fbe79f09f824badc26ebfff87efa6c646b7cf5

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          set -x
          # Mitigate GHSA-m425-mq94-257g / CVE-2023-44487 (grpc)
          go get google.golang.org/grpc@v1.57.1
          go mod tidy

          export CGO_ENABLED=0 GO111MODULE=on
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-yaml" \
            -ldflags="-s -w -X github.com/pulumi/pulumi-yaml/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-yaml/
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-yaml
    strip-prefix: v
