package:
  name: py3-botocore
  version: 1.34.11
  epoch: 0
  description: "The low-level, core functionality of Boto3"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-dateutil
      - py3-docutils
      - py3-jmespath
      - py3-urllib3
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
      expected-sha256: 51905c3d623c60df5dc5794387de7caf886d350180a01a3dfa762e903edb45a9

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 29738
