package:
  name: ruby3.2-openid_connect
  version: 2.2.1
  epoch: 0
  description: OpenID Connect Server & Client Library
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-activemodel
      - ruby3.2-attr_required
      - ruby3.2-faraday
      - ruby3.2-faraday-follow_redirects
      - ruby3.2-json-jwt
      - ruby3.2-rack-oauth2
      - ruby3.2-swd
      - ruby3.2-tzinfo
      - ruby3.2-validate_email
      - ruby3.2-validate_url
      - ruby3.2-webfinger

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2794070effa3c69f3a8da5cace088a98f22828f4e3dd121557016b1969f173ea
      uri: https://github.com/nov/openid_connect/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: openid_connect

update:
  enabled: true
  github:
    identifier: nov/openid_connect
    strip-prefix: v
