package:
  name: rye
  version: 0.16.0
  epoch: 0
  description: "An Experimental Package Management Solution for Python"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - perl
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mitsuhiko/rye
      expected-commit: c003223d5db575276d3ef52d31590580f3b1e97f
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/${{package.name}} ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: mitsuhiko/rye
