package:
  name: terragrunt
  version: 0.54.1
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1c3c3f79fc064a7a91c9a8872d03609c92dca94908bd21a0bd12b82481bab18e
      uri: https://github.com/gruntwork-io/terragrunt/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      go build -v -o bin/terragrunt -ldflags "-s -w -X  github.com/gruntwork-io/go-commons/version.Version=v${{package.version}}"
      install -Dm755 bin/terragrunt "${{targets.destdir}}"/usr/bin/terragrunt

  - uses: strip

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
