package:
  name: traefik
  version: 2.10.7
  epoch: 2
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/traefik/traefik
      expected-commit: 0a7964300166d167f68d5502bc245b3b9c8842b4
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v20.10.24 github.com/go-jose/go-jose/v3@v3.0.1 golang.org/x/crypto@v0.17.0

  - runs: |
      go mod edit -replace github.com/hashicorp/consul=github.com/hashicorp/consul@v1.14.7

      go mod tidy
      VERSION=v${{package.version}} ./script/make.sh generate binary
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv ./dist/traefik "${{targets.destdir}}"/usr/bin
      go version -m "${{targets.destdir}}"/usr/bin/traefik

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
