package:
  name: trivy
  version: 0.48.1
  epoch: 0
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}
      expected-commit: ba825b2ae1b0481d4b0d2845eafbb3cc83914c2f

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11
      go-version: "1.21.0"

  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-w -X=main.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/trivy" ./cmd/trivy

  - uses: strip

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v
