package:
  name: trivy
  version: 0.48.0
  epoch: 0
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/aquasecurity/trivy/archive/v${{package.version}}/trivy-${{package.version}}.tar.gz
      expected-sha512: a9966dad0c16a12bcfbced45489a41f940bdbe7b4b44ee6845fef63523e84d1cccc20c732681708d4234eda91ca4e98d0e97c8d17041ea066599165e0309aa85

  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-w -X=main.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/trivy" ./cmd/trivy

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 141362
