package:
  name: xsimd
  version: 12.1.0
  epoch: 0
  description: "C++ wrappers for SIMD intrinsics and parallelized, optimized mathematical functions (SSE, AVX, NEON, AVX512)"
  copyright:
    - license: "BSD-3-Clause"

environment:
  contents:
    packages:
      - build-base
      - cmake
      - samurai
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/xtensor-stack/xsimd
      tag: ${{package.version}}
      expected-commit: bd6e9f848933018031c5a67f09ba48e84ebabe7b

  - runs: |
      cmake -B build -G Ninja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DBUILD_SHARED_LIBS=ONs \
      -DCMAKE_BUILD_TYPE=MinSizeRel \
      -DBUILD_TESTS=OFF
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: "xsimd-dev"
    description: "C++ wrappers for SIMD intrinsics and parallelized, optimized mathematical functions (SSE, AVX, NEON, AVX512) (development files)"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: xtensor-stack/xsimd
    use-tag: true
