package:
  name: zarf
  version: 0.32.0
  epoch: 0
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/defenseunicorns/zarf
      expected-commit: 93e80e83d758943346d41730da68072dd767c35a
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: zarf
      ldflags: -s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=v${{package.version}}'

  - uses: strip

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
