name: Wolfictl Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      id: lint
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:5ec0d52957cd2aa174e68b03ef872d3bec94d5136d07bb2758806c8301a08576
      with:
        entrypoint: wolfictl
        args: lint --skip-rule no-makefile-entry-for-package
    - name: Enforce YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:5ec0d52957cd2aa174e68b03ef872d3bec94d5136d07bb2758806c8301a08576
      with:
        entrypoint: wolfictl
        args: lint yam
